#!/usr/bin/env ruby
require 'miniharvest'
require 'nokogiri'

mh = MiniHarvest::MiniHarvest.new
mh.oai_base_uri = ARGV[0]
mh.set = ARGV[1]
mh.from = ARGV[2]
mh.marc_collection = Nokogiri::XML('<collection xmlns="http://www.loc.gov/MARC21/slim">')
marc_xml = mh.get_records(mh.initial_request)
File.write(ARGV[3], marc_xml.to_xml)
